#!/usr/bin/env bash

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

$DIR/ghcjs cabal new-configure $1 --enable-benchmarks --project-file=$DIR/cabal-ghcjs.project --builddir=$DIR/dist/ghcjs/exe/$1/
