name: pure-dom
author: Sean Hickman
latest: 0.8.0.0
published: 2020-06-19
license: BSD3
repository: github.com/grumply/pure-dom.git
homepage: purehs.org/packages/pure-dom
collaborators: []
tags:
  - core
  - internal
  - dom
short: |
  Rendering and reconciliation algorithm 
description: |
  The core rendering and reconciliation algorithm for Pure.hs applications.