name: pure-core
author: Sean Hickman
latest: 0.8.0.0
published: 2020-06-17
license: BSD3
repository: github.com/grumply/pure-core.git
homepage: purehs.org/packages/pure-core
collaborators: []
tags:
  - core
  - internal
short: |
  Core Pure.hs types and patterns
description: |
  Core types, methods, and patterns used to implement all higher-level abstractions for server, service, and interface development in Pure.hs. 