email: sean@grumply.com
category: Web
ghc-options: '-Wall -fno-warn-unused-do-bind -rtsopts -threaded '
dependencies:
- base
- bytestring
- containers
- directory
- filepath
- http-types
- pandoc
- pure
- pure-cached
- pure-core
- pure-default
- pure-elm
- pure-json
- pure-render
- pure-server
- pure-tagsoup
- pure-time
- pure-try
- pure-txt
- pure-txt-interpolate
- pure-websocket
- text
- wai
- wai-app-static
- wai-extra
- warp
- yaml
- Glob
- shared
default-extensions:
- AutoDeriveTypeable
- BangPatterns
- ConstraintKinds
- DataKinds
- DefaultSignatures
- DeriveDataTypeable
- DeriveFoldable
- DeriveFunctor
- DeriveGeneric
- DeriveTraversable
- DoAndIfThenElse
- EmptyCase
- EmptyDataDecls
- ExistentialQuantification
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- GeneralizedNewtypeDeriving
- ImplicitParams
- InstanceSigs
- KindSignatures
- LambdaCase
- MultiParamTypeClasses
- MultiWayIf
- NamedFieldPuns
- OverloadedStrings
- PartialTypeSignatures
- PatternGuards
- PatternSynonyms
- PolyKinds
- RankNTypes
- RecordWildCards
- ScopedTypeVariables
- StandaloneDeriving
- TupleSections
- TypeApplications
- TypeFamilies
- TypeFamilyDependencies
- TypeOperators
- TypeSynonymInstances
- ViewPatterns
- TemplateHaskell
- PostfixOperators
- DerivingVia
- BlockArguments
name: backend
version: 0.1.0.0
synopsis: backend server
author: Sean Hickman
ghcjs-options: -O1 -threaded -dedupe -DGHCJS_BROWSER -DGHCJS_GC_INTERVAL=3000000 -DGHCJS_BUSY_YIELD=20
license: BSD3
executables:
  backend:
    source-dirs:
    - src
    main: Main.hs
    dependencies:
    - base
    - bytestring
    - containers
    - directory
    - filepath
    - http-types
    - pandoc
    - pure
    - pure-cached
    - pure-core
    - pure-default
    - pure-elm
    - pure-json
    - pure-render
    - pure-server
    - pure-tagsoup
    - pure-time
    - pure-try
    - pure-txt
    - pure-txt-interpolate
    - pure-websocket
    - text
    - wai
    - wai-app-static
    - wai-extra
    - warp
    - yaml
    - Glob
    - shared
