name: pure
author: Sean Hickman
latest: 0.8.0.0
published: 2020-06-18
license: BSD3
repository: github.com/grumply/pure.git
homepage: purehs.org/packages/pure
collaborators: []
tags:
  - base
  - internal
synopsis: |
  Pure.hs base library
description: |
  Base library that re-exports much of the Pure.hs ecosystem for easy import.
excerpt: |
  Base library that re-exports much of the core Pure.hs ecosystem for developing with HTML, CSS + themeing, and events.