name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]  

    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v8
    - uses: cachix/cachix-action@v5
      with:
        name: purehs

    - name: optimized build
      run: |
        nix-env -iA nixpkgs.pkgs.closurecompiler
        ./ghc npm run prod:backend
        ./ghcjs npm run prod:frontend
        du -sh ./dist/ghc/build/*/ghc-*/backend-*/x/backend/opt/build/backend/backend
        du -sh ./dist/site/main.js
        du -sh ./dist/site/main.js.min
        du -sh ./dist/site/main.js.min.gz
